# This workflow will test a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Tests

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.0
        
    - name: Download dependencies
      run: |
        go mod download
        go mod verify

    - name: Test
      run: go test -covermode=count -coverprofile=coverage.out ./...
    
    - name: Upload test coverage to Coveralls.io
      uses: shogo82148/actions-goveralls@v1
      with:
          path-to-profile: coverage.out